export const SHOW_ADD_SETTINGS = 'SHOW_ADD_SETTINGS';
export const HIDE_ADD_SETTINGS = 'HIDE_ADD_SETTINGS';
export const SHOW_RESULTS_PANEL = 'SHOW_RESULTS_PANEL';
export const HIDE_RESULTS_PANEL = 'HIDE_RESULTS_PANEL';
export const SHOW_RESULTS_MODAL = 'SHOW_RESULTS_MODAL';
export const HIDE_RESULTS_MODAL = 'HIDE_RESULTS_MODAL';
export const TOGGLE_SCROLL = 'TOGGLE_SCROLL';
export const SHOW_ERROR_WINDOW = 'SHOW_ERROR_WINDOW';
export const HIDE_ERROR_WINDOW = 'HIDE_ERROR_WINDOW';
export const SHOW_AUTH_FORM = 'SHOW_AUTH_FORM';
// **********************************

export const GET_TOKEN = 'GET_TOKEN';
export const CHANGE_COORDS = 'CHANGE_COORDS';
export const CHANGE_RADIUS = 'CHANGE_RADIUS';
export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_START_SEARCH_TIME = 'CHANGE_START_SEARCH_TIME';
export const CHANGE_END_SEARCH_TIME = 'CHANGE_END_SEARCH_TIME';
export const CHANGE_WORD_SEARCH = 'CHANGE_WORD_SEARCH';

// ***************************************

export const CHANGE_TYPE_SEARCH = 'ADD_SETTINGS_PANEL/CHANGE_TYPE_SEARCH';
export const TOGGLE_EXT_SEARCH = 'ADD_SETTINGS_PANEL/TOGGLE_EXT_SEARCH';
export const CHANGE_SEARCH_DEPTH = 'ADD_SETTINGS_PANEL/CHANGE_SEARCH_DEPTH';
export const TOGGLE_IMAGE_RESOLUTION = 'ADD_SETTINGS_PANEL/TOGGLE_IMAGE_RESOLUTION';

export const CHANGE_SEX = 'ADD_SETTINGS_PANEL/CHANGE_SEX';
export const CHANGE_AGE = 'ADD_SETTINGS_PANEL/CHANGE_AGE';
export const CHANGE_CITY = 'ADD_SETTINGS_PANEL/CHANGE_CITY';
export const CHANGE_RELATION = 'ADD_SETTINGS_PANEL/CHANGE_RELATION';
export const TOGGLE_COMMON_FRIEND = 'ADD_SETTINGS_PANEL/TOGGLE_COMMON_FRIEND';

export const CHANGE_GROUP_CITY = 'ADD_SETTINGS_PANEL/CHANGE_GROUP_CITY';
export const CHANGE_MEMBERS_COUNT = 'ADD_SETTINGS_PANEL/CHANGE_MEMBERS_COUNT';

// ***************************************
export const LOAD_DATA = 'LOAD_DATA';
export const ADD_PART_DATA_TO_DISPLAY = 'ADD_PART_DATA_TO_DISPLAY';
export const CLEAR_DATA_FROM_CONTAINER = 'CLEAR_DATA_FROM_CONTAINER';
